### ISSUE TITLE
Conventional Commits changelog generator creates malformed markdown syntax

### ISSUE THREAD

**Issue by OptimusCrime** [SpareBank1/designsystem#116]
### Which package is this issue related to?

All [packages](https://github.com/SpareBank1/designsystem/tree/master/packages).

### Describe your issue

The [Conventional Commits](https://conventionalcommits.org/) changelog generator package seem to create malformed/incorrect markdown syntax.

**Example (from [ffe-core/CHANGELOG.md](https://github.com/SpareBank1/designsystem/blob/master/packages/ffe-core/CHANGELOG.md))**

#### - Malformed markup

```
# Change Log

All notable changes to this project will be documented in this file.
See [Conventional Commits](https://conventionalcommits.org) for commit guidelines.

      <a name="12.0.2"></a>
## [12.0.2](https://github.com/SpareBank1/designsystem/compare/@sb1/ffe-core@12.0.0...@sb1/ffe-core@12.0.2) (2018-03-07)
```

#### - Resulting changelog file

![ffecore-changelog](https://user-images.githubusercontent.com/2326278/37826716-e6ea7fca-2e94-11e8-9960-19b86e573db6.png)

### Expected behavior

The lines `      <a name="xx.yy.zz"></a>` should not be there.

**Comment by kwltrs** [comment]
This does not happen with all packages, but some CHANGELOGs are indented as expected (e.g. [ffe-cards](https://github.com/SpareBank1/designsystem/blob/7e918f7429c388602ef9fd53f56deba08dfc3199/packages/ffe-cards/CHANGELOG.md)). Some research shows that this unexpected indentation is caused by [dedent](https://github.com/dmnd/dedent), which lerna uses when generating the CHANGLOG files. I think this is not a bug in dedent, lerna or one of the involved conventional-changelog-packages, but rather something with the formatting of our CHANGELOG, which causes dedent to  keep the indention.
