### ISSUE TITLE
ffe-datepicker-react: Date is rendered with a border for all months

### ISSUE THREAD

**Issue by wkillerud** [SpareBank1/designsystem#13]
Steps to reproduce:

1. Select a date in the calendar widget
2. Use the next or previous button to change month

Expected behavior: the date should be rendered as selected only for the actual month I selected
Actual behavior: the date is rendered as selected for all months

**Comment by selbekk** [comment]
Hm, is the issue title a bit off here @wkillerud ?

**Comment by wkillerud** [comment]
Waaay off. Copy paste gone wrong. Will fix.

**Comment by henrikhermansen** [comment]
The bug title and description is not really correct here.
While it's not completely wrong, it's important to notice there are two modifiers for `ffe-calendar__date`: `selected` and `focus`.
When you navigate the months, after selecting a date, it's only the `focus` modifier that stays on the day-of-month you selected. The `selected` modifier correctly renders only on the month where you actually selected a date.

The following image shows the difference between the two modifiers:
![image](https://user-images.githubusercontent.com/435037/36784674-8d3a5afc-1c80-11e8-8afa-60566755316d.png) ![image](https://user-images.githubusercontent.com/435037/36785007-ad149cc4-1c81-11e8-88da-ecabeb86209e.png)
Dark blue background for `selected`, blue border for `focus`.

Given this information
- is this correct behaviour?
- if not, should we fix it? I ask this question because I suspect it may cause more complexity for keyboard navigation.

**Comment by selbekk** [comment]
I think the way you described it made sense - is this really a bug?

**Comment by wkillerud** [comment]
@henrikhermansen Aha, that makes sense. This issue is from the internal archives :female_detective: Sounds like it's working as intended. I'll close the issue as wontfix.
