### ISSUE TITLE
ffe-accordion animerer pila over Z-aksen

### ISSUE THREAD

**Issue by wkillerud** [SpareBank1/designsystem#180]
Under [animasjoner](https://design.sparebank1.no/visuell-identitet.html#visuell-identitet_animasjoner) beskriver vi at vi animerer "bevegelse i X- og Y-aksen - ikke Z (3D)". 

Vi bryter med det prinsippet i [ffe-accordion](https://design.sparebank1.no/styleguidist/index.html#accordion-1) :male_detective:  Vi bør endre animasjonen så den følger guidelines som er definert under _Visuell identitet_.

**Comment by benmatthews** [comment]
The css is actually using `rotateX(180deg)` which rotates around the x axis.  I guess a simple solution to this is to just use `rotate(180deg)` but then the GPU is not going to be used... so maybe the right solution is to use `rotateZ(180deg)`

**Comment by ivarni** [comment]
I'm fairly sure we can live without GPU acceleration for this one :)

**Comment by adidick-zz** [comment]
I think it's safe to stick to the X-Y rules for the sake of consistency here.
I personally think the 180 spin is a bit weird visually in regards to the way the field actually expands (rotate ≠ expand) so that's something we could look into in regards to how all of our transitional animations work. It would be nice to visually support the action.

**Comment by wkillerud** [comment]
Solved in #225
