### ISSUE TITLE
Spinner is shaking in IE11

### ISSUE THREAD

**Issue by selbekk** [SpareBank1/designsystem#186]
#### Which package is this issue related to?
ffe-spinner

#### Describe your issue (screenshots welcome!)
The spinner (both small and large) shakes very slightly in IE11. Tried to make a gif of it:

![brrrrrrrr](https://user-images.githubusercontent.com/1307267/38980912-5f8d1148-43be-11e8-97e9-a6c488e97784.gif)

#### What is the expected behavior? 
Not to get epilepsy

#### What is the actual behavior?

![brrrrr](https://media.giphy.com/media/JEGIloZ79M46c/giphy.gif)

#### Steps to reproduce

You can open [this page](https://design.sparebank1.no/styleguidist/index.html#!/Spinner) in IE11 and notice it for yourself

**Comment by ivarni** [comment]
It's been like this for as long as I can remember.

**Comment by selbekk** [comment]
Looks like it's a good ol' IE bug. A quick google search suggested trying to change the transform slightly, to "trick" IE into doing the right thing. ([example](https://stackoverflow.com/questions/42558183/ie-10-11-edge-shaky-on-hover-animation))

**Comment by benmatthews** [comment]
`transform-origin: 50.01%` did not seem to fix the problem... neither does adding some hardware accelerated css like `transform: translate3d(0,0,0)` or ` transform: translateZ(0)`.

I think we could create more fun and interesting spinners by using an inline svg instead of styling a pseudo element.  This would be easy to add to the react packages but might mean a bit more work for people only using the css modules.  I have to admit though I have not tested `transform: rotate` on an svg in IE yet.

**Comment by selbekk** [comment]
@benmatthews unfortunately - IE doesn't support animating SVGs with CSS, so that's kind of a show-stopper :(

**Comment by ivarni** [comment]
What @selbekk said. If I recall correctly we have some SVGs where we've just accepted that animation won't happen in IE but that's not really an option for a spinner.

I'm pretty sure it's possible to do this in IE with just DOM and CSS though, if we wanted to spend the time on it.

**Comment by wkillerud** [comment]
I had a look at this issue today, and from what I could tell moving the animation out from the pseudo-element fixed the shaking for `ffe-spinner`. In other words animating the actual `span` instead of `::before`. Unfortunately it had no effect on the spinner inside the buttons when I did the same thing there (they don't share code) :sob:
