### ISSUE TITLE
ShortcutButton no longer supports loading state

### ISSUE THREAD

**Issue by ivarni** [SpareBank1/designsystem#199]
#### Which package is this issue related to?

`ffe-buttons`/`ffe-buttons-react`

#### Describe your issue (screenshots welcome!)

The support for a loading state seems to have been removed from `ShortcutButton` although this does not seem to be mentioned in the changelog. As a result, we're now stuck with a button that just becomes a white box when we try to set the loading state.

#### What is the expected behavior? 

Breaking changes should be clearly indicated so that we can handle this when upgrading to new majors. It would be nice if this support could be re-introduced as a patch-version and then if it's not desired to support it there could be a new major release where it is explicitly removed again.

#### What is the actual behavior?

Our loading shortcut-button looks like this:

![image](https://user-images.githubusercontent.com/379849/39114741-fbd5b522-46df-11e8-92fc-f43969a5875d.png)

#### Steps to reproduce

Set `isLoading` prop on a `ShortcutButton`

**Comment by ivarni** [comment]
So was the removal of this intentional or not? Does it need to get re-removed in a new breaking major?

**Comment by wkillerud** [comment]
Cc @selbekk

**Comment by selbekk** [comment]
It was indeed intentional - shortcut buttons (per the old design documentation) were meant for links IIRC - and links typically don't have spinners. If you want that behavior, you can use a secondary button, which doesn't have an animated icon that "pulls" you into the next page by jumping to the right on hover.

It may have been an oversight on my part though - perhaps @adidick can give us the final verdict on whether this should be a part of our button catalogue or not.

Either way I'm sorry for not mentioning it in the release notes - that was definitely my bad.

**Comment by adidick-zz** [comment]
@selbekk is correct here in that "Shortcut button" does not have a loading state. It is in fact a link that takes you directly to another page, hence no loading state. In the example image above it looks like an action button could be better suited (depending on the intended function of the button and text used in the button). For example, if it takes you straight to a process page where you can start filling in your details in order to find out how much it will cost, you could use an action button instead.

**Comment by adidick-zz** [comment]
Where is the screengrab from @ivarni ?

**Comment by ivarni** [comment]
@adidick Spinn in kfp-skade.

I can make a breaking change to remove it again but then Someone™️ is going to have to decide how to deal with that the next time kfp-skade gets its version updated.
