### ISSUE TITLE
ffe-webfonts: Minification strips away font license

### ISSUE THREAD

**Issue by wkillerud** [SpareBank1/designsystem#233]
#### Which package is this issue related to?

`ffe-webfonts`

#### Describe your issue

The license is stripped away during minification

#### What is the expected behavior? 

The license should use a common mechanism for indicating it shouldn't be stripped away, like for instance [Normalize.css](https://github.com/SpareBank1/designsystem/blob/36dc3a255a300b3639b727ccdef8729c24a6a036/packages/ffe-core/less/normalize.css#L1). 

#### What is the actual behavior?

The licence is stripped away.

#### Steps to reproduce

Turn on minimization of CSS in the design system. See license comments are stripped away.

**Comment by ivarni** [comment]
What we've done is to have the comment block start with `/*!` instead of `/**`. This apparently is magic syntax to tell [clean-css](https://github.com/jakubpawlowicz/clean-css) to not strip the comment during minification. [[1]](https://stash.intern.sparebank1.no/projects/KFP/repos/kfp-aksept/browse/kfp-aksept-client/src/index.html.js#61-104)

But there is no way we can guarantee that a consumer's build process doesn't strip it out. They could be using different tooling. I seem to recall a discussion around this where we decided this is ultimately going to have to be the consumer's responsibility.

That being said, we should make sure it's not stripped from the designsystem, which seems to already be the case, but we could maybe minimize during the designsystem build process and use that magic comment to still keep the license. Lead by example?

**Comment by ivarni** [comment]
Ah, and then I clicked your link to see that the comment is exactly what you were linking to :)

**Comment by ivarni** [comment]
And now I see you've made a PR already. Good thing I'm paid by the hour. Anyway, at least now the issue itself contains a bit more information if someone stumbles over it later ;)

**Comment by wkillerud** [comment]
Fixed in #235
