### ISSUE TITLE
Export colors and breakpoints as JS variables!

### ISSUE THREAD

**Issue by selbekk** [SpareBank1/designsystem#246]
#### Which package is this issue related to?
ffe-core

#### Describe your feature request
I want to start using CSS-in-JS in one of our apps, and I would love to have the LESS variables in ffe-core available in JavaScript as well.

I'm suggesting writing a script that would extract variables from the ffe-core LESS files, and expose them as named exports of the `ffe-core` package.

**Comment by ivarni** [comment]
Last time we discussed this it stranded on how we're going to handle animations. Do we have a strategy for that now?

**Comment by ivarni** [comment]
I don't think we should start exposing these things untill we know how to solve the harder problems that will come down the road so I'd advice to do that locally first.

**Comment by selbekk** [comment]
Animations isn't a part of this issue imo. It can be solved in a different PR - but be exposed in a similar fashion later on.

Actually, if you're using css-in-js, animations can be solved this way too! :) We'd just expose the motion.less variables as well, and they could then be used in css-in-js keyframes. For JS-only, I'm sure there is some kind of library that could translate the css string to a JavaScript easing function. [Here's one](https://github.com/gre/bezier-easing).

That being said, I don't think this discussion should be a part of this issue.

**Comment by ivarni** [comment]
The issue that stopped us was figuring out how to have the easing-functions match the CSS easings, seeing as we have a standard for animations that should behave the same across the board.

I understand that this has nothing to do with colors but if we introduce this for colors it's going to grow if people start using it and IMHO we should decide on how to handle that before it becomes an issue and we're already exposing the static half of the CSS.

That's why I believe it should mature a bit in a local project *before* its moved here and "officially supported".
