### ISSUE TITLE
Normalize padding props for the grid

### ISSUE THREAD

**Issue by ivarni** [SpareBank1/designsystem#282]
#### Which package is this issue related to?

`ffe-grid-react` (mayhaps `ffe-grid`)

#### Describe your issue (screenshots welcome!)

I'm getting a bit fed up trying to remember what the padding props are called

Grid: `noTopPadding`
GridRow: `topPadding`
GridCol: `noBottomPadding`

It's annoying having to remember which ones have the negative prefix and which ones do not. 

My suggestion is to at the very least give them all names like `topPadding` and `bottomPadding` and set defaults accordingly. Perhaps we could also add props so they all have `top` and `bottom` props but that would also require changes in `ffe-grid`.

This would be a breaking change, but not the most difficult one to migrate to.

Thoughts?

**Comment by wkillerud** [comment]
Consistency would be nice, and I like the idea of using both `true` and `false` in the same prop rather than having a named prop for each case.

Regarding adding missing props, I'm a bit wary of adding modifiers before we get designs that need them. I suppose for top- and bottom padding in a grid it should be safe to do though 🤔 

Maybe we should use `oneOf([true])` (or `false` if that makes more sense semantically) rather than adding classes for the sake of completion?

**Comment by ivarni** [comment]
I'm fine with not adding new classes to the CSS, it's less work that way and it's still an improvement if I only have to rememeber that cols deal with bottom padding while rows and grids have top padding.
