### ISSUE TITLE
Browser autocomplete triggering on SearchableDropdown

### ISSUE THREAD

**Issue by paandahl** [SpareBank1/designsystem#287]
#### Which package is this issue related to?

`ffe-searchable-dropdown-react`

#### Describe your issue (screenshots welcome!)

SearchableDropdown gets autocomplete-list if the field has been submitted before.

![screenshot-1](https://user-images.githubusercontent.com/44539/41354943-95c5865e-6f20-11e8-829c-e2f390ffa52d.png)

#### What is the expected behavior? 

On this component, autocomplete breaks the layout, and is not expected to show up.

#### Fix suggestion

I'll make a PR where autoComplete is introduced as a prop on the contained `<InputField>`, and set to "off" in the `<SearchableDropdown>` component.

**Comment by ivarni** [comment]
There's no need to make a property for this, there is already native DOM attributes for controlling it. Using [this pattern](https://github.com/SpareBank1/designsystem/blob/develop/CONTRIBUTING.md#videresend-props) with letting the consumer pass arbitrary  props via a destructured pass-on-props variable means we don't have to explicitly expand the API for things like this, and that we don't alias well-known DOM attributes.

It would be great if you could introduce this pattern with a `...rest` variable instead.

**Comment by ivarni** [comment]
Although one could argue that this component shouldn't have autocomplete enabled ever, due to its nature. In that case, we don't need an API prop for it at all.

I think the ideal solution is to just disable autocomplete by default *and* introducing the rest-pass-on described in CONTRIBUTING.md linked above.

**Comment by paandahl** [comment]
`<InputField>` is a clear candidate for passing rest-props, but in the case of `<SearchableDropdown>`, the `<InputField>` is just one of several sub-components it renders. Do you think I should:

a) Pass on the rest-props to the `<InputField>` (since it's the main input rendered)
b) Make a new prop, `inputProps`, that takes an object, and spreads it onto `<InputField>`
c) Drop rest-props on `<SearchableDropdown>` and just set `autoComplete='off`' on its `<InputField>`

**Comment by ivarni** [comment]
I've seen the `inputProps` approach being used in other components but I think that's mainly where there is a need to pass props to different sub-components, so I'd vote  for *b)* or just fixing the problem at hand with *c)*.

I'm betting @selbekk is going to recommend a render-function, which is also an option here :)

On that note, we're pretty much just using [downshift](https://www.npmjs.com/package/downshift) in our apps I think.

**Comment by selbekk** [comment]
The officially documented [render props`](https://reactjs.org/docs/render-props.html) technique is nice and all - but not the appropriate approach here. We don't ever want autocomplete on a searchable dropdown, because we implement our own "autocomplete" in a way. Therefore I suggest we follow your third recommendation, and just turn off autocomplete on the input field. Easy fix!
