### ISSUE TITLE
ffe-checkbox-react: disable prop grayout

### ISSUE THREAD

**Issue by ksawerysb1** [SpareBank1/designsystem#292]
#### Which package is this issue related to?
ffe-checkbox-react
#### Describe your issue (screenshots welcome!)
Setting the disabled prop does not result in a grayed out checkbox, might be confusing if an element doesn't change it's status when clicked but is not visibly represented as disabled.
#### What is the expected behavior? 
Some visual indication that the element is disabled, usually it is a grayout and a special hover mouse pointer.
#### What is the actual behavior?
The mouse pointer only changes on the border. The element doesn't change appearance otherwise.
#### Steps to reproduce
Set disabled=true on a ffe-checkbox-react

**Comment by wkillerud** [comment]
We deliberately don't have support for `disabled` state in most of our components. Instead we let the user try to make changes, validate those changes, and show helpful error messages under the parts of the form that are in an invalid state. Users often don't understand why a form component is disabled and get frustrated.

If there's a good reason for using `disabled` then we might add it to the design system, but run this by design/UX if you haven't already @ksawerysb1.

**Comment by ksawerysb1** [comment]
There are some tables with a dense grid of checkboxes that need some sort of indication that some fields can't be edited based data in the system. Adding a message to each "disabled" checkbox would make the table unreadable. The graphic disabled grayout would at least give an indication why the checkbox doesn't "work" when clicked. Maybe we could come up with a popup/hover type of message if the user clicks on the disabled field anyway?

**Comment by selbekk** [comment]
Could you perhaps skip rendering the checkbox altogether?

**Comment by ksawerysb1** [comment]
Empty spaces in a checkbox grid were not something the designers wanted.
The override selector is: "input[type="checkbox"]:disabled + label::before" so it's relatively easy to set it but would be convenient if the component had the default disabled background.

**Comment by selbekk** [comment]
The reason we don't support this today is because we don't want to use disabled form elements at all in our design system. We've decided that it's much better UX - in most cases - to explain why something is not available through other means.

I fully understand that this won't work in your case - and applying a custom style in your case is probably what you should do. As far as I've understood the discussion in the design system forum meetings, however, it's not something we want to encourage on a general level by supporting it out of the box.
