### ISSUE TITLE
Possible to set size of <headingX />

### ISSUE THREAD

**Issue by pethel** [SpareBank1/designsystem#427]
Feature request:

A common requirement that also often leads to problematic, unsemantic HTML is that some developers try to follow a design given by a designer and  sees the `<Heading6 />`  in the design guide that has the perfect size according to the design given by the designer.

The developer just uses the  `<Heading6 />`  without thinking about its semantic meaning. That it also would need a   `<Heading1 />`,  `<Heading2 />`,  `<Heading3 />`,  `<Heading4 />` and `<Heading5 />` to make sense.  

For that reason I wonder if it could be an idea to provide a size for these headers as a prop?
```
<Heading1 size="5" />
```

**Comment by pethel** [comment]
Sorry just found this props `lookLike`. So maybe its just about documenting it

**Comment by selbekk** [comment]
Yeah that's my bad. It's hard to document through styleguidist because I'm using a ["component factory"](https://github.com/SpareBank1/designsystem/blob/develop/packages/ffe-core-react/src/typography/Heading.js#L52-L57) pattern to create these components.

I'd be open to look at a pull request trying to improve this documentation though!

Closing this one - feel free to open a new issue / pr for the documentation.
