### ISSUE TITLE
Enhancement: Button focus styling looks bad on colored backgrounds. 

### ISSUE THREAD

**Issue by Miyagee** [SpareBank1/designsystem#459]
#### Which package is this issue related to?

Action button or the button styling in general. 

#### Describe your issue (screenshots welcome!)

The button focus styling looks horrible on all other background colors than white. 

![image](https://user-images.githubusercontent.com/9053491/46856924-009ab800-ce08-11e8-9635-55b5f8c0ae9e.png)

An alternative is to give the color opacity like so: 

![image](https://user-images.githubusercontent.com/9053491/46857112-7dc62d00-ce08-11e8-9993-c82876eedae5.png)

    box-shadow: 0 0 0 1px #fff, 0 0 0 4px rgba(161, 223, 255, 0.4)

instead of: 

    box-shadow: 0 0 0 1px #fff, 0 0 0 4px #a1dfff
  
This still gives a pleasant tint to focusing on white backgrounds. 

![image](https://user-images.githubusercontent.com/9053491/46857774-009bb780-ce0a-11e8-86e0-ff6ea5bddf6c.png)

#### What is the expected behavior? 

Look good.

#### What is the actual behavior?

Look horrendous.

#### Steps to reproduce

Focus a button which has a parent with a background color other than white or white~ish.

**Comment by antidecaf** [comment]
The focus outline was recently updated in order to increase the contrast to different backgrounds. The previous value did have an alpha transparency, which was a part of the problem.

Here's the original issue: #11 
And a merged PR with a fix: #407 

If we were to update it again, it should be considered by GD/IxD first. Thoughts, @adidick?

**Comment by adidick-zz** [comment]
As @antidecaf said, this has just been updated, so it isn't something that I'm willing to take up in the design forums again.
 
@Miyagee - The main problem with the previous focus state was that it failed accessibly tests and didn't work on various background colours. The new version is designed to be more visible and remain in sync with our focus colour that we use throughout. Your suggestion goes a little bit back towards the "not visible enough" variation of old. In addition, the darker blue colour will be too strong when used on white or lighter backgrounds.

I hope you can live with its horrendousness?

**Comment by Miyagee** [comment]
@adidick I'm fine with it as it is pretty easy to override the styling. It was more to bring some awareness to the problem so that maybe the component itself could be made more modular to support those cases.

**Comment by antidecaf** [comment]
Overriding stuff like this is a simple task indeed, but doing so kind of defeats the purpose of using a design system.

While we do appreciate having issues like this brought to our attention, in this case the perceived horrendousness of the current look seems to pose a smaller problem than the accessibility related issues of the suggested solution/previous implementation. If you feel like the outline needs a revamp, I suggest talking to your team's design resource in order to sketch an alternative solution and have it reviewed in the GD/IxD forums. We'll be happy to add a fix with their go-ahead. :)

**Comment by adidick-zz** [comment]
@Miyagee As Anders said, any issues with the current solution should be taken up in the appropriate design forum. The example you've shown above on a white background has what I suspect to be not enough contrast as is very faint on the white background, which essentially defeats the whole point of showing that the button is in focus. 

As Anders also mentioned, overriding these items without a good reason goes against everything the design system stands for and takes us back a step, rather than improving upon it by working together and moving forward.
