### ISSUE TITLE
Styleguide: Flash of unstyled content when opening components page

### ISSUE THREAD

**Issue by antidecaf** [SpareBank1/designsystem#48]
When navigating to [components](http://design.sparebank1.no/styleguidist/index.html) from a different page in the styleguide, there is a flash of unstyled content before the styling kicks in and saves the day. The problem is not present in other pages.

![screenshot from 2018-03-02 15-42-58](https://user-images.githubusercontent.com/463847/36904346-c06516a4-1e30-11e8-9c37-d8f767632a8d.png)

**Comment by wkillerud** [comment]
I can take a look at this - I suppose we can move Less compilation to an `npm` script and add a `link` tag in `head` instead of bundling styles together with the JavaScript.

**Comment by wkillerud** [comment]
On second thought, that would make local development more difficult. Maybe `ExtractTextPlugin`? Anyway, I'll give it a shot and open a PR for discussion.

**Comment by kwltrs** [comment]
Maybe a production build, that links the two stylesheets instead of insourcing(?) them, could solve this issue. Also, having a link tag to `/styles.css` would be a slight improvement as these styles only apply to the header and navigation and would not affect local development (if one is not working on the header or navigation).

**Comment by wkillerud** [comment]
Merged the improvements. They'll need to be published though, and as far as I can tell from #3 it's a manual process. @antidecaf, you fix? :bowing_man:

**Comment by antidecaf** [comment]
^ @kwltrs 👼
