### ISSUE TITLE
Radioswitch: aria-invalid is set on both buttons for fieldMessage

### ISSUE THREAD

**Issue by joannae** [SpareBank1/designsystem#520]
#### Which package is this issue related to?
ffe-radio-button-react: RadioSwitch

#### Describe your issue (screenshots welcome!)
If fieldMessage is sendt inn as a prop to RadioSwitch, both buttons are marked with a red ring (only visible on the unmarked choice) and aria-invalid.
![screenshot from 2018-11-22 16-16-45](https://user-images.githubusercontent.com/6974641/48932564-f71f6800-eefc-11e8-851b-2b948445e8e7.png)

#### What is the expected behavior? 
Expected is that only the selected button is marked as invalid. Otherwise it indicated that no matter what the user does, it's wrong. However, if no button is selected both buttons should be marked as invalid.

![screenshot from 2018-11-23 09-05-48](https://user-images.githubusercontent.com/6974641/48933044-08697400-eeff-11e8-8713-d523dc66d54f.png)

#### What is the actual behavior?
No matter what button the user has selected, both buttons are marked av invalid.

#### Steps to reproduce
Send in fieldMessage to the RadioSwitch.

**Comment by ivarni** [comment]
Since `RadioSwitch` only has two options I'm thinking we could just assume that the selected option is wrong if there is one, so that if we get the aria-invalid prop from the `InputGroup` we'll set in on both radios if there's no selected value and only on the selected one if there is a selected value. We'll probably also need to fix the CSS so that we can show a selected radio with a red ring.

You'll find relevant css [here](https://github.com/SpareBank1/designsystem/blob/develop/packages/ffe-form/less/radio-switch.less) and [here](https://github.com/SpareBank1/designsystem/blob/develop/packages/ffe-form/less/input-group.less)
