### ISSUE TITLE
ffe-system-message: Close icon renders on top of text

### ISSUE THREAD

**Issue by fossecode** [SpareBank1/designsystem#693]
#### Which package is this issue related to?
ffe-system-message

#### Describe your issue (screenshots welcome!)
![image](https://user-images.githubusercontent.com/8818089/64474040-b5e80400-d16e-11e9-8b8b-37ecbbb7c017.png)

#### What is the expected behavior? 
The close icon and the text should not overlap

#### What is the actual behavior?
The close icon overlaps the text

**Comment by ivarni** [comment]
![image](https://user-images.githubusercontent.com/379849/64508520-f4e89780-d2dd-11e9-841a-06421fabc6d9.png)

Most of the time this doesn't happen but it seems a bit luck-based. Perhaps using a flexbox container instead of just setting the `<p>` width to 90% and hoping for the best would be bettter.

**Comment by pethel** [comment]
Løst

**Comment by fossecode** [comment]
![image](https://user-images.githubusercontent.com/8818089/89317253-6a3f2280-d67d-11ea-9aeb-80724cbfca4d.png)
Ser ut som at dette fortsatt er et problem for ffe-context-message.
