### ISSUE TITLE
ffe-core: better export of variables

### ISSUE THREAD

**Issue by henrikhermansen** [SpareBank1/designsystem#720]
#### Which package is this issue related to?
ffe-core

#### Describe your issue (screenshots welcome!)
I would love to be able to import JS variables from ffe-core in this syntax:
`import { orangeFire } from '@sb1/ffe-core';` and still have code completion in IntelliJ.

As it is now, I have to use either
`import { orangeFire } from '@sb1/ffe-core/lib/colors';` or
`import coreVars from '@sb1/ffe-core';` and use props like `coreVars.orangeFire`
to get code completion.

#### Ideas to fix this
ffe-icons-react also exports some generated JS, and this package works great.

As it is now, this is ffe-core/lib/index.js
```
module.exports = Object.assign(
    {},
    require('./colors'),
    require('./breakpoints')
);
```

while ffe-icons-react has a lot of magic and stuff like this:
```
Object.defineProperty(exports, "BamseIkon", {
  enumerable: true,
  get: function get() {
    return _bamseIkon.default;
  }
});
```

Could we use this as inspiration to improve ffe-core?

#### Steps to reproduce
Try to import JS variables from ffe-core in the syntax I desire, and see if you get code completion in IntelliJ.

**Comment by steffenz** [comment]
As this is working as described in Visual Studio Code, it seems to be more of an IDE issue, rather than code. Upon testing however, it seems to work in the same manner in IntelliJ too (maybe an update has fixed this issue?). I've created two projects with create-react-app; one with and one without TypeScript. It seems to work with both flavors (both in IntelliJ and VSCode).

**IntelliJ version:**
IntelliJ IDEA 2019.3.3 (Ultimate Edition)
Build #IU-193.6494.35, built on February 11, 2020

**VSCode Version:**
Version: 1.40.2

**Screenshots:**
![intellijintellisense](https://user-images.githubusercontent.com/1404818/76065874-c564d000-5f8c-11ea-848e-e03396206464.png)

![vscode](https://user-images.githubusercontent.com/1404818/76065884-cb5ab100-5f8c-11ea-81a3-2a00aafe0f91.png)

It seems to me like this has magically has been resolved (time heals all bugs?), and I'm closing this issue for now. Feel free to re-open or post a reply if I've misunderstood the real issue here! :smile:
